[theme]
inherit = "basic"
stylesheets = [
    "styles/cs1302_base.css",
]
sidebars = [
    "localtoc.html",
    "relations.html",
    "sourcelink.html",
    "searchbox.html",
]
pygments_style = { default = "monokai", dark = "monokai" }

[options]
